// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configures various aspects of Dataform code compilation.
public struct CodeCompilationConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The default database (Google Cloud project ID).
  public var defaultDatabase: Swift.String = Swift.String()

  /// Optional. The default schema (BigQuery dataset ID).
  public var defaultSchema: Swift.String = Swift.String()

  /// Optional. The default BigQuery location to use. Defaults to "US".
  /// See the BigQuery docs for a full list of locations:
  /// https://cloud.google.com/bigquery/docs/locations.
  public var defaultLocation: Swift.String = Swift.String()

  /// Optional. The default schema (BigQuery dataset ID) for assertions.
  public var assertionSchema: Swift.String = Swift.String()

  /// Optional. User-defined variables that are made available to project code
  /// during compilation.
  public var vars: [Swift.String: Swift.String] = [:]

  /// Optional. The suffix that should be appended to all database (Google Cloud
  /// project ID) names.
  public var databaseSuffix: Swift.String = Swift.String()

  /// Optional. The suffix that should be appended to all schema (BigQuery
  /// dataset ID) names.
  public var schemaSuffix: Swift.String = Swift.String()

  /// Optional. The prefix that should be prepended to all table names.
  public var tablePrefix: Swift.String = Swift.String()

  /// Optional. The prefix to prepend to built-in assertion names.
  public var builtinAssertionNamePrefix: Swift.String = Swift.String()

  /// Optional. The default notebook runtime options.
  public var defaultNotebookRuntimeOptions: NotebookRuntimeOptions? = nil

  /// Optional. The pipeline options which defines the pipeline type and path
  /// within the Git repository.
  public var pipelineConfig: PipelineConfig? = nil

  /// Output only. Whether OpenLineage events are emitted for actions in this
  /// workflow. Reflects the `lineage.enabled` setting from
  /// `workflow_settings.yaml`.
  public var lineageEnabled: Swift.Bool? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CodeCompilationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CodeCompilationConfig().with { $0.defaultDatabase = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let defaultDatabase = CodingKeys(stringValue: "defaultDatabase")
    static let defaultSchema = CodingKeys(stringValue: "defaultSchema")
    static let defaultLocation = CodingKeys(stringValue: "defaultLocation")
    static let assertionSchema = CodingKeys(stringValue: "assertionSchema")
    static let vars = CodingKeys(stringValue: "vars")
    static let databaseSuffix = CodingKeys(stringValue: "databaseSuffix")
    static let schemaSuffix = CodingKeys(stringValue: "schemaSuffix")
    static let tablePrefix = CodingKeys(stringValue: "tablePrefix")
    static let builtinAssertionNamePrefix = CodingKeys(stringValue: "builtinAssertionNamePrefix")
    static let defaultNotebookRuntimeOptions = CodingKeys(
      stringValue: "defaultNotebookRuntimeOptions")
    static let pipelineConfig = CodingKeys(stringValue: "pipelineConfig")
    static let lineageEnabled = CodingKeys(stringValue: "lineageEnabled")

    static let _knownKeys: Set<Swift.String> = [
      "defaultDatabase",
      "defaultSchema",
      "defaultLocation",
      "assertionSchema",
      "vars",
      "databaseSuffix",
      "schemaSuffix",
      "tablePrefix",
      "builtinAssertionNamePrefix",
      "defaultNotebookRuntimeOptions",
      "pipelineConfig",
      "lineageEnabled",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .defaultDatabase) {
      self.defaultDatabase = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .defaultSchema) {
      self.defaultSchema = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .defaultLocation) {
      self.defaultLocation = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .assertionSchema) {
      self.assertionSchema = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .vars) {
      self.vars = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .databaseSuffix) {
      self.databaseSuffix = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .schemaSuffix) {
      self.schemaSuffix = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tablePrefix) {
      self.tablePrefix = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .builtinAssertionNamePrefix)
    {
      self.builtinAssertionNamePrefix = value
    }
    self.defaultNotebookRuntimeOptions = try container.decodeIfPresent(
      NotebookRuntimeOptions.self, forKey: .defaultNotebookRuntimeOptions)
    self.pipelineConfig = try container.decodeIfPresent(
      PipelineConfig.self, forKey: .pipelineConfig)
    self.lineageEnabled = try container.decodeIfPresent(Swift.Bool.self, forKey: .lineageEnabled)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.defaultDatabase, forKey: .defaultDatabase)
    try container.encode(self.defaultSchema, forKey: .defaultSchema)
    try container.encode(self.defaultLocation, forKey: .defaultLocation)
    try container.encode(self.assertionSchema, forKey: .assertionSchema)
    try container.encode(self.vars, forKey: .vars)
    try container.encode(self.databaseSuffix, forKey: .databaseSuffix)
    try container.encode(self.schemaSuffix, forKey: .schemaSuffix)
    try container.encode(self.tablePrefix, forKey: .tablePrefix)
    try container.encode(self.builtinAssertionNamePrefix, forKey: .builtinAssertionNamePrefix)
    try container.encodeIfPresent(
      self.defaultNotebookRuntimeOptions, forKey: .defaultNotebookRuntimeOptions)
    try container.encodeIfPresent(self.pipelineConfig, forKey: .pipelineConfig)
    try container.encodeIfPresent(self.lineageEnabled, forKey: .lineageEnabled)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.CodeCompilationConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
