// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Configures various aspects of Dataform code compilation.
public struct CodeCompilationConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The default database (Google Cloud project ID).
  public var defaultDatabase: Swift.String = Swift.String()

  /// Optional. The default schema (BigQuery dataset ID).
  public var defaultSchema: Swift.String = Swift.String()

  /// Optional. The default BigQuery location to use. Defaults to "US".
  /// See the BigQuery docs for a full list of locations:
  /// https://cloud.google.com/bigquery/docs/locations.
  public var defaultLocation: Swift.String = Swift.String()

  /// Optional. The default schema (BigQuery dataset ID) for assertions.
  public var assertionSchema: Swift.String = Swift.String()

  /// Optional. User-defined variables that are made available to project code
  /// during compilation.
  public var vars: [Swift.String: Swift.String] = [:]

  /// Optional. The suffix that should be appended to all database (Google Cloud
  /// project ID) names.
  public var databaseSuffix: Swift.String = Swift.String()

  /// Optional. The suffix that should be appended to all schema (BigQuery
  /// dataset ID) names.
  public var schemaSuffix: Swift.String = Swift.String()

  /// Optional. The prefix that should be prepended to all table names.
  public var tablePrefix: Swift.String = Swift.String()

  /// Optional. The prefix to prepend to built-in assertion names.
  public var builtinAssertionNamePrefix: Swift.String = Swift.String()

  /// Optional. The default notebook runtime options.
  public var defaultNotebookRuntimeOptions: NotebookRuntimeOptions? = nil

  /// Optional. The pipeline options which defines the pipeline type and path
  /// within the Git repository.
  public var pipelineConfig: PipelineConfig? = nil

  /// Initialize a new instance of `CodeCompilationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CodeCompilationConfig().with { $0.defaultDatabase = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.CodeCompilationConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
