// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// `CommitRepositoryChanges` request message.
public struct CommitRepositoryChangesRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The repository's name.
  public var name: Swift.String = Swift.String()

  /// Required. The changes to commit to the repository.
  public var commitMetadata: CommitMetadata? = nil

  /// Optional. The commit SHA which must be the repository's current HEAD before
  /// applying this commit; otherwise this request will fail. If unset, no
  /// validation on the current HEAD commit SHA is performed.
  public var requiredHeadCommitSha: Swift.String = Swift.String()

  /// Optional. A map to the path of the file to the operation. The path is the
  /// full file path including filename, from repository root.
  public var fileOperations: [Swift.String: CommitRepositoryChangesRequest.FileOperation] = [:]

  /// Initialize a new instance of `CommitRepositoryChangesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CommitRepositoryChangesRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Represents a single file operation to the repository.
  public struct FileOperation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The operation to perform on the file.
    public var operation: OneOf_Operation? = nil

    /// Initialize a new instance of `FileOperation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FileOperation().with { $0.writeFile = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case writeFile = "writeFile"
      case deleteFile = "deleteFile"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var operation: OneOf_Operation? = nil
      let operationCheckAndSet = {
        if operation != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'operation'"))
        }
        operation = $0
      }
      if let writeFile = try container.decodeIfPresent(
        CommitRepositoryChangesRequest.FileOperation.WriteFile?.self, forKey: .writeFile)
      {
        try operationCheckAndSet(.writeFile(writeFile))
      }
      if let deleteFile = try container.decodeIfPresent(
        CommitRepositoryChangesRequest.FileOperation.DeleteFile?.self, forKey: .deleteFile)
      {
        try operationCheckAndSet(.deleteFile(deleteFile))
      }
      self.operation = operation
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.operation {
        switch choice {
        case .writeFile(let value):
          try container.encode(value, forKey: .writeFile)
        case .deleteFile(let value):
          try container.encode(value, forKey: .deleteFile)
        }
      }
    }

    /// Represents the write file operation (for files added or modified).
    public struct WriteFile: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// The file's contents.
      public var contents: Foundation.Data = Foundation.Data()

      /// Initialize a new instance of `WriteFile`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = WriteFile().with { $0.contents = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dataform.v1.CommitRepositoryChangesRequest.FileOperation.WriteFile"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Represents the delete file operation.
    public struct DeleteFile: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Initialize a new instance of `DeleteFile`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = DeleteFile().with { $0.<placeholder> = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dataform.v1.CommitRepositoryChangesRequest.FileOperation.DeleteFile"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// The operation to perform on the file.
    public enum OneOf_Operation: Codable, Equatable, Sendable {
      /// Represents the write operation.
      indirect case writeFile(CommitRepositoryChangesRequest.FileOperation.WriteFile?)
      /// Represents the delete operation.
      indirect case deleteFile(CommitRepositoryChangesRequest.FileOperation.DeleteFile?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.dataform.v1.CommitRepositoryChangesRequest.FileOperation"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.CommitRepositoryChangesRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
