// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a single Dataform action in a compilation result.
public struct CompilationResultAction: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// This action's identifier. Unique within the compilation result.
  public var target: Target? = nil

  /// The action's identifier if the project had been compiled without any
  /// overrides configured. Unique within the compilation result.
  public var canonicalTarget: Target? = nil

  /// The full path including filename in which this action is located, relative
  /// to the workspace root.
  public var filePath: Swift.String = Swift.String()

  /// Output only. All the metadata information that is used internally to serve
  /// the resource. For example: timestamps, flags, status fields, etc. The
  /// format of this field is a JSON string.
  public var internalMetadata: Swift.String? = nil

  /// The compiled object.
  public var compiledObject: OneOf_CompiledObject? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CompilationResultAction`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CompilationResultAction().with { $0.relation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let relation = CodingKeys(stringValue: "relation")
    static let operations = CodingKeys(stringValue: "operations")
    static let assertion = CodingKeys(stringValue: "assertion")
    static let declaration = CodingKeys(stringValue: "declaration")
    static let notebook = CodingKeys(stringValue: "notebook")
    static let dataPreparation = CodingKeys(stringValue: "dataPreparation")
    static let target = CodingKeys(stringValue: "target")
    static let canonicalTarget = CodingKeys(stringValue: "canonicalTarget")
    static let filePath = CodingKeys(stringValue: "filePath")
    static let internalMetadata = CodingKeys(stringValue: "internalMetadata")

    static let _knownKeys: Set<Swift.String> = [
      "relation",
      "operations",
      "assertion",
      "declaration",
      "notebook",
      "dataPreparation",
      "target",
      "canonicalTarget",
      "filePath",
      "internalMetadata",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.target = try container.decodeIfPresent(Target.self, forKey: .target)
    self.canonicalTarget = try container.decodeIfPresent(Target.self, forKey: .canonicalTarget)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filePath) {
      self.filePath = value
    }
    self.internalMetadata = try container.decodeIfPresent(
      Swift.String.self, forKey: .internalMetadata)

    var compiledObject: OneOf_CompiledObject? = nil
    let compiledObjectCheckAndSet = {
      if compiledObject != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'compiledObject'"))
      }
      compiledObject = $0
    }
    if let relation = try container.decodeIfPresent(
      CompilationResultAction.Relation?.self, forKey: .relation)
    {
      try compiledObjectCheckAndSet(.relation(relation))
    }
    if let operations = try container.decodeIfPresent(
      CompilationResultAction.Operations?.self, forKey: .operations)
    {
      try compiledObjectCheckAndSet(.operations(operations))
    }
    if let assertion = try container.decodeIfPresent(
      CompilationResultAction.Assertion?.self, forKey: .assertion)
    {
      try compiledObjectCheckAndSet(.assertion(assertion))
    }
    if let declaration = try container.decodeIfPresent(
      CompilationResultAction.Declaration?.self, forKey: .declaration)
    {
      try compiledObjectCheckAndSet(.declaration(declaration))
    }
    if let notebook = try container.decodeIfPresent(
      CompilationResultAction.Notebook?.self, forKey: .notebook)
    {
      try compiledObjectCheckAndSet(.notebook(notebook))
    }
    if let dataPreparation = try container.decodeIfPresent(
      CompilationResultAction.DataPreparation?.self, forKey: .dataPreparation)
    {
      try compiledObjectCheckAndSet(.dataPreparation(dataPreparation))
    }
    self.compiledObject = compiledObject
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.target, forKey: .target)
    try container.encodeIfPresent(self.canonicalTarget, forKey: .canonicalTarget)
    try container.encode(self.filePath, forKey: .filePath)
    try container.encodeIfPresent(self.internalMetadata, forKey: .internalMetadata)

    if let choice = self.compiledObject {
      switch choice {
      case .relation(let value):
        try container.encode(value, forKey: .relation)
      case .operations(let value):
        try container.encode(value, forKey: .operations)
      case .assertion(let value):
        try container.encode(value, forKey: .assertion)
      case .declaration(let value):
        try container.encode(value, forKey: .declaration)
      case .notebook(let value):
        try container.encode(value, forKey: .notebook)
      case .dataPreparation(let value):
        try container.encode(value, forKey: .dataPreparation)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents a database relation.
  public struct Relation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A list of actions that this action depends on.
    public var dependencyTargets: [Target] = []

    /// Whether this action is disabled (i.e. should not be run).
    public var disabled: Swift.Bool = Swift.Bool()

    /// Arbitrary, user-defined tags on this action.
    public var tags: [Swift.String] = []

    /// Descriptor for the relation and its columns.
    public var relationDescriptor: RelationDescriptor? = nil

    /// The type of this relation.
    public var relationType: CompilationResultAction.Relation.RelationType = CompilationResultAction
      .Relation.RelationType()

    /// The SELECT query which returns rows which this relation should contain.
    public var selectQuery: Swift.String = Swift.String()

    /// SQL statements to be executed before creating the relation.
    public var preOperations: [Swift.String] = []

    /// SQL statements to be executed after creating the relation.
    public var postOperations: [Swift.String] = []

    /// Configures `INCREMENTAL_TABLE` settings for this relation. Only set if
    /// `relation_type` is `INCREMENTAL_TABLE`.
    public var incrementalTableConfig: CompilationResultAction.Relation.IncrementalTableConfig? =
      nil

    /// The SQL expression used to partition the relation.
    public var partitionExpression: Swift.String = Swift.String()

    /// A list of columns or SQL expressions used to cluster the table.
    public var clusterExpressions: [Swift.String] = []

    /// Sets the partition expiration in days.
    public var partitionExpirationDays: Swift.Int32 = Swift.Int32()

    /// Specifies whether queries on this table must include a predicate filter
    /// that filters on the partitioning column.
    public var requirePartitionFilter: Swift.Bool = Swift.Bool()

    /// Additional options that will be provided as key/value pairs into the
    /// options clause of a create table/view statement. See
    /// https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language
    /// for more information on which options are supported.
    public var additionalOptions: [Swift.String: Swift.String] = [:]

    /// Optional. The connection specifying the credentials to be used to read
    /// and write to external storage, such as Cloud Storage. The connection can
    /// have the form `{project}.{location}.{connection_id}` or
    /// `projects/{project}/locations/{location}/connections/{connection_id}`,
    /// or be set to DEFAULT.
    public var connection: Swift.String = Swift.String()

    /// Optional. The table format for the BigQuery table.
    public var tableFormat: CompilationResultAction.Relation.TableFormat = CompilationResultAction
      .Relation.TableFormat()

    /// Optional. The file format for the BigQuery table.
    public var fileFormat: CompilationResultAction.Relation.FileFormat = CompilationResultAction
      .Relation.FileFormat()

    /// Optional. The fully qualified location prefix of the external folder
    /// where table data is stored. The URI should be in the format
    /// `gs://bucket/path_to_table/`.
    public var storageUri: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Relation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Relation().with { $0.dependencyTargets = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let dependencyTargets = CodingKeys(stringValue: "dependencyTargets")
      static let disabled = CodingKeys(stringValue: "disabled")
      static let tags = CodingKeys(stringValue: "tags")
      static let relationDescriptor = CodingKeys(stringValue: "relationDescriptor")
      static let relationType = CodingKeys(stringValue: "relationType")
      static let selectQuery = CodingKeys(stringValue: "selectQuery")
      static let preOperations = CodingKeys(stringValue: "preOperations")
      static let postOperations = CodingKeys(stringValue: "postOperations")
      static let incrementalTableConfig = CodingKeys(stringValue: "incrementalTableConfig")
      static let partitionExpression = CodingKeys(stringValue: "partitionExpression")
      static let clusterExpressions = CodingKeys(stringValue: "clusterExpressions")
      static let partitionExpirationDays = CodingKeys(stringValue: "partitionExpirationDays")
      static let requirePartitionFilter = CodingKeys(stringValue: "requirePartitionFilter")
      static let additionalOptions = CodingKeys(stringValue: "additionalOptions")
      static let connection = CodingKeys(stringValue: "connection")
      static let tableFormat = CodingKeys(stringValue: "tableFormat")
      static let fileFormat = CodingKeys(stringValue: "fileFormat")
      static let storageUri = CodingKeys(stringValue: "storageUri")

      static let _knownKeys: Set<Swift.String> = [
        "dependencyTargets",
        "disabled",
        "tags",
        "relationDescriptor",
        "relationType",
        "selectQuery",
        "preOperations",
        "postOperations",
        "incrementalTableConfig",
        "partitionExpression",
        "clusterExpressions",
        "partitionExpirationDays",
        "requirePartitionFilter",
        "additionalOptions",
        "connection",
        "tableFormat",
        "fileFormat",
        "storageUri",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Target].self, forKey: .dependencyTargets) {
        self.dependencyTargets = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
        self.disabled = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
        self.tags = value
      }
      self.relationDescriptor = try container.decodeIfPresent(
        RelationDescriptor.self, forKey: .relationDescriptor)
      if let value = try container.decodeIfPresent(
        CompilationResultAction.Relation.RelationType.self, forKey: .relationType)
      {
        self.relationType = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .selectQuery) {
        self.selectQuery = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .preOperations) {
        self.preOperations = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .postOperations) {
        self.postOperations = value
      }
      self.incrementalTableConfig = try container.decodeIfPresent(
        CompilationResultAction.Relation.IncrementalTableConfig.self,
        forKey: .incrementalTableConfig)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .partitionExpression)
      {
        self.partitionExpression = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .clusterExpressions)
      {
        self.clusterExpressions = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int32.self, forKey: .partitionExpirationDays)
      {
        self.partitionExpirationDays = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .requirePartitionFilter)
      {
        self.requirePartitionFilter = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .additionalOptions)
      {
        self.additionalOptions = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .connection) {
        self.connection = value
      }
      if let value = try container.decodeIfPresent(
        CompilationResultAction.Relation.TableFormat.self, forKey: .tableFormat)
      {
        self.tableFormat = value
      }
      if let value = try container.decodeIfPresent(
        CompilationResultAction.Relation.FileFormat.self, forKey: .fileFormat)
      {
        self.fileFormat = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .storageUri) {
        self.storageUri = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.dependencyTargets, forKey: .dependencyTargets)
      try container.encode(self.disabled, forKey: .disabled)
      try container.encode(self.tags, forKey: .tags)
      try container.encodeIfPresent(self.relationDescriptor, forKey: .relationDescriptor)
      try container.encode(self.relationType, forKey: .relationType)
      try container.encode(self.selectQuery, forKey: .selectQuery)
      try container.encode(self.preOperations, forKey: .preOperations)
      try container.encode(self.postOperations, forKey: .postOperations)
      try container.encodeIfPresent(self.incrementalTableConfig, forKey: .incrementalTableConfig)
      try container.encode(self.partitionExpression, forKey: .partitionExpression)
      try container.encode(self.clusterExpressions, forKey: .clusterExpressions)
      try container.encode(self.partitionExpirationDays, forKey: .partitionExpirationDays)
      try container.encode(self.requirePartitionFilter, forKey: .requirePartitionFilter)
      try container.encode(self.additionalOptions, forKey: .additionalOptions)
      try container.encode(self.connection, forKey: .connection)
      try container.encode(self.tableFormat, forKey: .tableFormat)
      try container.encode(self.fileFormat, forKey: .fileFormat)
      try container.encode(self.storageUri, forKey: .storageUri)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Contains settings for relations of type `INCREMENTAL_TABLE`.
    public struct IncrementalTableConfig: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The SELECT query which returns rows which should be inserted into the
      /// relation if it already exists and is not being refreshed.
      public var incrementalSelectQuery: Swift.String = Swift.String()

      /// Whether this table should be protected from being refreshed.
      public var refreshDisabled: Swift.Bool = Swift.Bool()

      /// A set of columns or SQL expressions used to define row uniqueness.
      /// If any duplicates are discovered (as defined by `unique_key_parts`),
      /// only the newly selected rows (as defined by `incremental_select_query`)
      /// will be included in the relation.
      public var uniqueKeyParts: [Swift.String] = []

      /// A SQL expression conditional used to limit the set of existing rows
      /// considered for a merge operation (see `unique_key_parts` for more
      /// information).
      public var updatePartitionFilter: Swift.String = Swift.String()

      /// SQL statements to be executed before inserting new rows into the
      /// relation.
      public var incrementalPreOperations: [Swift.String] = []

      /// SQL statements to be executed after inserting new rows into the
      /// relation.
      public var incrementalPostOperations: [Swift.String] = []

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `IncrementalTableConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = IncrementalTableConfig().with { $0.incrementalSelectQuery = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let incrementalSelectQuery = CodingKeys(stringValue: "incrementalSelectQuery")
        static let refreshDisabled = CodingKeys(stringValue: "refreshDisabled")
        static let uniqueKeyParts = CodingKeys(stringValue: "uniqueKeyParts")
        static let updatePartitionFilter = CodingKeys(stringValue: "updatePartitionFilter")
        static let incrementalPreOperations = CodingKeys(stringValue: "incrementalPreOperations")
        static let incrementalPostOperations = CodingKeys(stringValue: "incrementalPostOperations")

        static let _knownKeys: Set<Swift.String> = [
          "incrementalSelectQuery",
          "refreshDisabled",
          "uniqueKeyParts",
          "updatePartitionFilter",
          "incrementalPreOperations",
          "incrementalPostOperations",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(
          Swift.String.self, forKey: .incrementalSelectQuery)
        {
          self.incrementalSelectQuery = value
        }
        if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .refreshDisabled) {
          self.refreshDisabled = value
        }
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .uniqueKeyParts) {
          self.uniqueKeyParts = value
        }
        if let value = try container.decodeIfPresent(
          Swift.String.self, forKey: .updatePartitionFilter)
        {
          self.updatePartitionFilter = value
        }
        if let value = try container.decodeIfPresent(
          [Swift.String].self, forKey: .incrementalPreOperations)
        {
          self.incrementalPreOperations = value
        }
        if let value = try container.decodeIfPresent(
          [Swift.String].self, forKey: .incrementalPostOperations)
        {
          self.incrementalPostOperations = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.incrementalSelectQuery, forKey: .incrementalSelectQuery)
        try container.encode(self.refreshDisabled, forKey: .refreshDisabled)
        try container.encode(self.uniqueKeyParts, forKey: .uniqueKeyParts)
        try container.encode(self.updatePartitionFilter, forKey: .updatePartitionFilter)
        try container.encode(self.incrementalPreOperations, forKey: .incrementalPreOperations)
        try container.encode(self.incrementalPostOperations, forKey: .incrementalPostOperations)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction.Relation.IncrementalTableConfig"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Indicates the type of this relation.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum RelationType: Codable, Equatable, Hashable, Sendable {
      /// Default value. This value is unused.
      case unspecified
      /// The relation is a table.
      case table
      /// The relation is a view.
      case view
      /// The relation is an incrementalized table.
      case incrementalTable
      /// The relation is a materialized view.
      case materializedView
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .table: return 1
        case .view: return 2
        case .incrementalTable: return 3
        case .materializedView: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "RELATION_TYPE_UNSPECIFIED"
        case .table: return "TABLE"
        case .view: return "VIEW"
        case .incrementalTable: return "INCREMENTAL_TABLE"
        case .materializedView: return "MATERIALIZED_VIEW"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RelationType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "RELATION_TYPE_UNSPECIFIED": self = .unspecified
        case "TABLE": self = .table
        case "VIEW": self = .view
        case "INCREMENTAL_TABLE": self = .incrementalTable
        case "MATERIALIZED_VIEW": self = .materializedView
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RelationType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .table
        case 2: self = .view
        case 3: self = .incrementalTable
        case 4: self = .materializedView
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("RELATION_TYPE_UNSPECIFIED")
        case .table: return try container.encode("TABLE")
        case .view: return try container.encode("VIEW")
        case .incrementalTable: return try container.encode("INCREMENTAL_TABLE")
        case .materializedView: return try container.encode("MATERIALIZED_VIEW")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Supported table formats for BigQuery tables.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum TableFormat: Codable, Equatable, Hashable, Sendable {
      /// Default value.
      case unspecified
      /// Apache Iceberg format.
      case iceberg
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .iceberg: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TABLE_FORMAT_UNSPECIFIED"
        case .iceberg: return "ICEBERG"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TableFormat/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TABLE_FORMAT_UNSPECIFIED": self = .unspecified
        case "ICEBERG": self = .iceberg
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TableFormat/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .iceberg
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("TABLE_FORMAT_UNSPECIFIED")
        case .iceberg: return try container.encode("ICEBERG")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Supported file formats for BigQuery tables.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum FileFormat: Codable, Equatable, Hashable, Sendable {
      /// Default value.
      case unspecified
      /// Apache Parquet format.
      case parquet
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .parquet: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "FILE_FORMAT_UNSPECIFIED"
        case .parquet: return "PARQUET"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FileFormat/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "FILE_FORMAT_UNSPECIFIED": self = .unspecified
        case "PARQUET": self = .parquet
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FileFormat/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .parquet
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("FILE_FORMAT_UNSPECIFIED")
        case .parquet: return try container.encode("PARQUET")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction.Relation"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Represents a list of arbitrary database operations.
  public struct Operations: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A list of actions that this action depends on.
    public var dependencyTargets: [Target] = []

    /// Whether this action is disabled (i.e. should not be run).
    public var disabled: Swift.Bool = Swift.Bool()

    /// Arbitrary, user-defined tags on this action.
    public var tags: [Swift.String] = []

    /// Descriptor for any output relation and its columns. Only set if
    /// `has_output` is true.
    public var relationDescriptor: RelationDescriptor? = nil

    /// A list of arbitrary SQL statements that will be executed without
    /// alteration.
    public var queries: [Swift.String] = []

    /// Whether these operations produce an output relation.
    public var hasOutput: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Operations`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Operations().with { $0.dependencyTargets = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let dependencyTargets = CodingKeys(stringValue: "dependencyTargets")
      static let disabled = CodingKeys(stringValue: "disabled")
      static let tags = CodingKeys(stringValue: "tags")
      static let relationDescriptor = CodingKeys(stringValue: "relationDescriptor")
      static let queries = CodingKeys(stringValue: "queries")
      static let hasOutput = CodingKeys(stringValue: "hasOutput")

      static let _knownKeys: Set<Swift.String> = [
        "dependencyTargets",
        "disabled",
        "tags",
        "relationDescriptor",
        "queries",
        "hasOutput",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Target].self, forKey: .dependencyTargets) {
        self.dependencyTargets = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
        self.disabled = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
        self.tags = value
      }
      self.relationDescriptor = try container.decodeIfPresent(
        RelationDescriptor.self, forKey: .relationDescriptor)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .queries) {
        self.queries = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .hasOutput) {
        self.hasOutput = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.dependencyTargets, forKey: .dependencyTargets)
      try container.encode(self.disabled, forKey: .disabled)
      try container.encode(self.tags, forKey: .tags)
      try container.encodeIfPresent(self.relationDescriptor, forKey: .relationDescriptor)
      try container.encode(self.queries, forKey: .queries)
      try container.encode(self.hasOutput, forKey: .hasOutput)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction.Operations"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Represents an assertion upon a SQL query which is required return zero
  /// rows.
  public struct Assertion: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A list of actions that this action depends on.
    public var dependencyTargets: [Target] = []

    /// The parent action of this assertion. Only set if this assertion was
    /// automatically generated.
    public var parentAction: Target? = nil

    /// Whether this action is disabled (i.e. should not be run).
    public var disabled: Swift.Bool = Swift.Bool()

    /// Arbitrary, user-defined tags on this action.
    public var tags: [Swift.String] = []

    /// The SELECT query which must return zero rows in order for this assertion
    /// to succeed.
    public var selectQuery: Swift.String = Swift.String()

    /// Descriptor for the assertion's automatically-generated view and its
    /// columns.
    public var relationDescriptor: RelationDescriptor? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Assertion`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Assertion().with { $0.dependencyTargets = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let dependencyTargets = CodingKeys(stringValue: "dependencyTargets")
      static let parentAction = CodingKeys(stringValue: "parentAction")
      static let disabled = CodingKeys(stringValue: "disabled")
      static let tags = CodingKeys(stringValue: "tags")
      static let selectQuery = CodingKeys(stringValue: "selectQuery")
      static let relationDescriptor = CodingKeys(stringValue: "relationDescriptor")

      static let _knownKeys: Set<Swift.String> = [
        "dependencyTargets",
        "parentAction",
        "disabled",
        "tags",
        "selectQuery",
        "relationDescriptor",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Target].self, forKey: .dependencyTargets) {
        self.dependencyTargets = value
      }
      self.parentAction = try container.decodeIfPresent(Target.self, forKey: .parentAction)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
        self.disabled = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
        self.tags = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .selectQuery) {
        self.selectQuery = value
      }
      self.relationDescriptor = try container.decodeIfPresent(
        RelationDescriptor.self, forKey: .relationDescriptor)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.dependencyTargets, forKey: .dependencyTargets)
      try container.encodeIfPresent(self.parentAction, forKey: .parentAction)
      try container.encode(self.disabled, forKey: .disabled)
      try container.encode(self.tags, forKey: .tags)
      try container.encode(self.selectQuery, forKey: .selectQuery)
      try container.encodeIfPresent(self.relationDescriptor, forKey: .relationDescriptor)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction.Assertion"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Represents a relation which is not managed by Dataform but which may be
  /// referenced by Dataform actions.
  public struct Declaration: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Descriptor for the relation and its columns. Used as documentation only,
    /// i.e. values here will result in no changes to the relation's metadata.
    public var relationDescriptor: RelationDescriptor? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Declaration`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Declaration().with { $0.relationDescriptor = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let relationDescriptor = CodingKeys(stringValue: "relationDescriptor")

      static let _knownKeys: Set<Swift.String> = [
        "relationDescriptor"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.relationDescriptor = try container.decodeIfPresent(
        RelationDescriptor.self, forKey: .relationDescriptor)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.relationDescriptor, forKey: .relationDescriptor)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction.Declaration"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Represents a notebook.
  public struct Notebook: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A list of actions that this action depends on.
    public var dependencyTargets: [Target] = []

    /// Whether this action is disabled (i.e. should not be run).
    public var disabled: Swift.Bool = Swift.Bool()

    /// The contents of the notebook.
    public var contents: Swift.String = Swift.String()

    /// Arbitrary, user-defined tags on this action.
    public var tags: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Notebook`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Notebook().with { $0.dependencyTargets = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let dependencyTargets = CodingKeys(stringValue: "dependencyTargets")
      static let disabled = CodingKeys(stringValue: "disabled")
      static let contents = CodingKeys(stringValue: "contents")
      static let tags = CodingKeys(stringValue: "tags")

      static let _knownKeys: Set<Swift.String> = [
        "dependencyTargets",
        "disabled",
        "contents",
        "tags",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Target].self, forKey: .dependencyTargets) {
        self.dependencyTargets = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
        self.disabled = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .contents) {
        self.contents = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
        self.tags = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.dependencyTargets, forKey: .dependencyTargets)
      try container.encode(self.disabled, forKey: .disabled)
      try container.encode(self.contents, forKey: .contents)
      try container.encode(self.tags, forKey: .tags)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction.Notebook"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines a compiled Data Preparation entity
  public struct DataPreparation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A list of actions that this action depends on.
    public var dependencyTargets: [Target] = []

    /// Whether this action is disabled (i.e. should not be run).
    public var disabled: Swift.Bool = Swift.Bool()

    /// Arbitrary, user-defined tags on this action.
    public var tags: [Swift.String] = []

    /// The definition for the data preparation.
    public var definition: OneOf_Definition? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DataPreparation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DataPreparation().with { $0.contentsYaml = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let contentsYaml = CodingKeys(stringValue: "contentsYaml")
      static let contentsSql = CodingKeys(stringValue: "contentsSql")
      static let dependencyTargets = CodingKeys(stringValue: "dependencyTargets")
      static let disabled = CodingKeys(stringValue: "disabled")
      static let tags = CodingKeys(stringValue: "tags")

      static let _knownKeys: Set<Swift.String> = [
        "contentsYaml",
        "contentsSql",
        "dependencyTargets",
        "disabled",
        "tags",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Target].self, forKey: .dependencyTargets) {
        self.dependencyTargets = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
        self.disabled = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
        self.tags = value
      }

      var definition: OneOf_Definition? = nil
      let definitionCheckAndSet = {
        if definition != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'definition'"))
        }
        definition = $0
      }
      if let contentsYaml = try container.decodeIfPresent(Swift.String.self, forKey: .contentsYaml)
      {
        try definitionCheckAndSet(.contentsYaml(contentsYaml))
      }
      if let contentsSql = try container.decodeIfPresent(
        CompilationResultAction.DataPreparation.SqlDefinition?.self, forKey: .contentsSql)
      {
        try definitionCheckAndSet(.contentsSql(contentsSql))
      }
      self.definition = definition
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.dependencyTargets, forKey: .dependencyTargets)
      try container.encode(self.disabled, forKey: .disabled)
      try container.encode(self.tags, forKey: .tags)

      if let choice = self.definition {
        switch choice {
        case .contentsYaml(let value):
          try container.encode(value, forKey: .contentsYaml)
        case .contentsSql(let value):
          try container.encode(value, forKey: .contentsSql)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Definition of a SQL Data Preparation
    public struct SqlDefinition: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The SQL query representing the data preparation steps. Formatted as a
      /// Pipe SQL query statement.
      public var query: Swift.String = Swift.String()

      /// Error table configuration,
      public var errorTable: CompilationResultAction.DataPreparation.ErrorTable? = nil

      /// Load configuration.
      public var load: CompilationResultAction.LoadConfig? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `SqlDefinition`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = SqlDefinition().with { $0.query = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let query = CodingKeys(stringValue: "query")
        static let errorTable = CodingKeys(stringValue: "errorTable")
        static let load = CodingKeys(stringValue: "load")

        static let _knownKeys: Set<Swift.String> = [
          "query",
          "errorTable",
          "load",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .query) {
          self.query = value
        }
        self.errorTable = try container.decodeIfPresent(
          CompilationResultAction.DataPreparation.ErrorTable.self, forKey: .errorTable)
        self.load = try container.decodeIfPresent(
          CompilationResultAction.LoadConfig.self, forKey: .load)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.query, forKey: .query)
        try container.encodeIfPresent(self.errorTable, forKey: .errorTable)
        try container.encodeIfPresent(self.load, forKey: .load)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction.DataPreparation.SqlDefinition"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Error table information, used to write error data into a BigQuery
    /// table.
    public struct ErrorTable: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Error Table target.
      public var target: Target? = nil

      /// Error table partition expiration in days. Only positive values are
      /// allowed.
      public var retentionDays: Swift.Int32 = Swift.Int32()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ErrorTable`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ErrorTable().with { $0.target = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let target = CodingKeys(stringValue: "target")
        static let retentionDays = CodingKeys(stringValue: "retentionDays")

        static let _knownKeys: Set<Swift.String> = [
          "target",
          "retentionDays",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.target = try container.decodeIfPresent(Target.self, forKey: .target)
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .retentionDays) {
          self.retentionDays = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.target, forKey: .target)
        try container.encode(self.retentionDays, forKey: .retentionDays)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction.DataPreparation.ErrorTable"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The definition for the data preparation.
    public enum OneOf_Definition: Codable, Equatable, Sendable {
      /// The data preparation definition, stored as a YAML string.
      case contentsYaml(Swift.String)
      /// SQL definition for a Data Preparation. Contains a SQL query and
      /// additional context information.
      indirect case contentsSql(CompilationResultAction.DataPreparation.SqlDefinition?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction.DataPreparation"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Simplified load configuration for actions
  public struct LoadConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Load mode
    public var mode: OneOf_Mode? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LoadConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LoadConfig().with { $0.replace = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let replace = CodingKeys(stringValue: "replace")
      static let append = CodingKeys(stringValue: "append")
      static let maximum = CodingKeys(stringValue: "maximum")
      static let unique = CodingKeys(stringValue: "unique")

      static let _knownKeys: Set<Swift.String> = [
        "replace",
        "append",
        "maximum",
        "unique",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var mode: OneOf_Mode? = nil
      let modeCheckAndSet = {
        if mode != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'mode'"))
        }
        mode = $0
      }
      if let replace = try container.decodeIfPresent(
        CompilationResultAction.SimpleLoadMode?.self, forKey: .replace)
      {
        try modeCheckAndSet(.replace(replace))
      }
      if let append = try container.decodeIfPresent(
        CompilationResultAction.SimpleLoadMode?.self, forKey: .append)
      {
        try modeCheckAndSet(.append(append))
      }
      if let maximum = try container.decodeIfPresent(
        CompilationResultAction.IncrementalLoadMode?.self, forKey: .maximum)
      {
        try modeCheckAndSet(.maximum(maximum))
      }
      if let unique = try container.decodeIfPresent(
        CompilationResultAction.IncrementalLoadMode?.self, forKey: .unique)
      {
        try modeCheckAndSet(.unique(unique))
      }
      self.mode = mode
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.mode {
        switch choice {
        case .replace(let value):
          try container.encode(value, forKey: .replace)
        case .append(let value):
          try container.encode(value, forKey: .append)
        case .maximum(let value):
          try container.encode(value, forKey: .maximum)
        case .unique(let value):
          try container.encode(value, forKey: .unique)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Load mode
    public enum OneOf_Mode: Codable, Equatable, Sendable {
      /// Replace destination table
      indirect case replace(CompilationResultAction.SimpleLoadMode?)
      /// Append into destination table
      indirect case append(CompilationResultAction.SimpleLoadMode?)
      /// Insert records where the value exceeds the previous maximum value for a
      /// column in the destination table
      indirect case maximum(CompilationResultAction.IncrementalLoadMode?)
      /// Insert records where the value of a column is not already present in
      /// the destination table
      indirect case unique(CompilationResultAction.IncrementalLoadMode?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction.LoadConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Simple load definition
  public struct SimpleLoadMode: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SimpleLoadMode`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SimpleLoadMode().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction.SimpleLoadMode"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Load definition for incremental load modes
  public struct IncrementalLoadMode: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Column name for incremental load modes
    public var column: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `IncrementalLoadMode`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IncrementalLoadMode().with { $0.column = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let column = CodingKeys(stringValue: "column")

      static let _knownKeys: Set<Swift.String> = [
        "column"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .column) {
        self.column = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.column, forKey: .column)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction.IncrementalLoadMode"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The compiled object.
  public enum OneOf_CompiledObject: Codable, Equatable, Sendable {
    /// The database relation created/updated by this action.
    indirect case relation(CompilationResultAction.Relation?)
    /// The database operations executed by this action.
    indirect case operations(CompilationResultAction.Operations?)
    /// The assertion executed by this action.
    indirect case assertion(CompilationResultAction.Assertion?)
    /// The declaration declared by this action.
    indirect case declaration(CompilationResultAction.Declaration?)
    /// The notebook executed by this action.
    indirect case notebook(CompilationResultAction.Notebook?)
    /// The data preparation executed by this action.
    indirect case dataPreparation(CompilationResultAction.DataPreparation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.CompilationResultAction"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
