// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents the result of compiling a Dataform project.
public struct CompilationResult: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The compilation result's name.
  public var name: Swift.String = Swift.String()

  /// Immutable. If set, fields of `code_compilation_config` override the default
  /// compilation settings that are specified in dataform.json.
  public var codeCompilationConfig: CodeCompilationConfig? = nil

  /// Output only. The fully resolved Git commit SHA of the code that was
  /// compiled. Not set for compilation results whose source is a workspace.
  public var resolvedGitCommitSha: Swift.String = Swift.String()

  /// Output only. The version of `@dataform/core` that was used for compilation.
  public var dataformCoreVersion: Swift.String = Swift.String()

  /// Output only. Errors encountered during project compilation.
  public var compilationErrors: [CompilationResult.CompilationError] = []

  /// Output only. Only set if the repository has a KMS Key.
  public var dataEncryptionState: DataEncryptionState? = nil

  /// Output only. The timestamp of when the compilation result was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. All the metadata information that is used internally to serve
  /// the resource. For example: timestamps, flags, status fields, etc. The
  /// format of this field is a JSON string.
  public var internalMetadata: Swift.String? = nil

  /// Output only. Metadata indicating whether this resource is user-scoped.
  /// `CompilationResult` resource is `user_scoped` only if it is sourced
  /// from a workspace.
  public var privateResourceMetadata: PrivateResourceMetadata? = nil

  /// Output only. Metadata about the repository snapshot used by scheduled
  /// notebooks.
  public var gcsRepositorySnapshotMetadata: GcsRepositorySnapshotMetadata? = nil

  /// The source of the compilation result.
  public var source: OneOf_Source? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `CompilationResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CompilationResult().with { $0.gitCommitish = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gitCommitish = CodingKeys(stringValue: "gitCommitish")
    static let workspace = CodingKeys(stringValue: "workspace")
    static let releaseConfig = CodingKeys(stringValue: "releaseConfig")
    static let name = CodingKeys(stringValue: "name")
    static let codeCompilationConfig = CodingKeys(stringValue: "codeCompilationConfig")
    static let resolvedGitCommitSha = CodingKeys(stringValue: "resolvedGitCommitSha")
    static let dataformCoreVersion = CodingKeys(stringValue: "dataformCoreVersion")
    static let compilationErrors = CodingKeys(stringValue: "compilationErrors")
    static let dataEncryptionState = CodingKeys(stringValue: "dataEncryptionState")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let internalMetadata = CodingKeys(stringValue: "internalMetadata")
    static let privateResourceMetadata = CodingKeys(stringValue: "privateResourceMetadata")
    static let gcsRepositorySnapshotMetadata = CodingKeys(
      stringValue: "gcsRepositorySnapshotMetadata")

    static let _knownKeys: Set<Swift.String> = [
      "gitCommitish",
      "workspace",
      "releaseConfig",
      "name",
      "codeCompilationConfig",
      "resolvedGitCommitSha",
      "dataformCoreVersion",
      "compilationErrors",
      "dataEncryptionState",
      "createTime",
      "internalMetadata",
      "privateResourceMetadata",
      "gcsRepositorySnapshotMetadata",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.codeCompilationConfig = try container.decodeIfPresent(
      CodeCompilationConfig.self, forKey: .codeCompilationConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resolvedGitCommitSha) {
      self.resolvedGitCommitSha = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataformCoreVersion) {
      self.dataformCoreVersion = value
    }
    if let value = try container.decodeIfPresent(
      [CompilationResult.CompilationError].self, forKey: .compilationErrors)
    {
      self.compilationErrors = value
    }
    self.dataEncryptionState = try container.decodeIfPresent(
      DataEncryptionState.self, forKey: .dataEncryptionState)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.internalMetadata = try container.decodeIfPresent(
      Swift.String.self, forKey: .internalMetadata)
    self.privateResourceMetadata = try container.decodeIfPresent(
      PrivateResourceMetadata.self, forKey: .privateResourceMetadata)
    self.gcsRepositorySnapshotMetadata = try container.decodeIfPresent(
      GcsRepositorySnapshotMetadata.self, forKey: .gcsRepositorySnapshotMetadata)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let gitCommitish = try container.decodeIfPresent(Swift.String.self, forKey: .gitCommitish) {
      try sourceCheckAndSet(.gitCommitish(gitCommitish))
    }
    if let workspace = try container.decodeIfPresent(Swift.String.self, forKey: .workspace) {
      try sourceCheckAndSet(.workspace(workspace))
    }
    if let releaseConfig = try container.decodeIfPresent(Swift.String.self, forKey: .releaseConfig)
    {
      try sourceCheckAndSet(.releaseConfig(releaseConfig))
    }
    self.source = source
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.codeCompilationConfig, forKey: .codeCompilationConfig)
    try container.encode(self.resolvedGitCommitSha, forKey: .resolvedGitCommitSha)
    try container.encode(self.dataformCoreVersion, forKey: .dataformCoreVersion)
    try container.encode(self.compilationErrors, forKey: .compilationErrors)
    try container.encodeIfPresent(self.dataEncryptionState, forKey: .dataEncryptionState)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.internalMetadata, forKey: .internalMetadata)
    try container.encodeIfPresent(self.privateResourceMetadata, forKey: .privateResourceMetadata)
    try container.encodeIfPresent(
      self.gcsRepositorySnapshotMetadata, forKey: .gcsRepositorySnapshotMetadata)

    if let choice = self.source {
      switch choice {
      case .gitCommitish(let value):
        try container.encode(value, forKey: .gitCommitish)
      case .workspace(let value):
        try container.encode(value, forKey: .workspace)
      case .releaseConfig(let value):
        try container.encode(value, forKey: .releaseConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// An error encountered when attempting to compile a Dataform project.
  public struct CompilationError: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. The error's top level message.
    public var message: Swift.String = Swift.String()

    /// Output only. The error's full stack trace.
    public var stack: Swift.String = Swift.String()

    /// Output only. The path of the file where this error occurred, if
    /// available, relative to the project root.
    public var path: Swift.String = Swift.String()

    /// Output only. The identifier of the action where this error occurred, if
    /// available.
    public var actionTarget: Target? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `CompilationError`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CompilationError().with { $0.message = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let message = CodingKeys(stringValue: "message")
      static let stack = CodingKeys(stringValue: "stack")
      static let path = CodingKeys(stringValue: "path")
      static let actionTarget = CodingKeys(stringValue: "actionTarget")

      static let _knownKeys: Set<Swift.String> = [
        "message",
        "stack",
        "path",
        "actionTarget",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .message) {
        self.message = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stack) {
        self.stack = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .path) {
        self.path = value
      }
      self.actionTarget = try container.decodeIfPresent(Target.self, forKey: .actionTarget)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.message, forKey: .message)
      try container.encode(self.stack, forKey: .stack)
      try container.encode(self.path, forKey: .path)
      try container.encodeIfPresent(self.actionTarget, forKey: .actionTarget)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataform.v1.CompilationResult.CompilationError"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The source of the compilation result.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Immutable. Git commit/tag/branch name at which the repository should be
    /// compiled. Must exist in the remote repository. Examples:
    /// - a commit SHA: `12ade345`
    /// - a tag: `tag1`
    /// - a branch name: `branch1`
    case gitCommitish(Swift.String)
    /// Immutable. The name of the workspace to compile. Must be in the format
    /// `projects/*/locations/*/repositories/*/workspaces/*`.
    case workspace(Swift.String)
    /// Immutable. The name of the release config to compile. Must be in the
    /// format `projects/*/locations/*/repositories/*/releaseConfigs/*`.
    case releaseConfig(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.CompilationResult"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
