// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// `ComputeRepositoryAccessTokenStatus` response message.
public struct ComputeRepositoryAccessTokenStatusResponse: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Indicates the status of the Git access token.
  public var tokenStatus: ComputeRepositoryAccessTokenStatusResponse.TokenStatus =
    ComputeRepositoryAccessTokenStatusResponse.TokenStatus()

  /// Initialize a new instance of `ComputeRepositoryAccessTokenStatusResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeRepositoryAccessTokenStatusResponse().with { $0.tokenStatus = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Indicates the status of a Git authentication token.
  public enum TokenStatus: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// The token could not be found in Secret Manager (or the Dataform
    /// Service Account did not have permission to access it).
    case notFound
    /// The token could not be used to authenticate against the Git remote.
    case invalid
    /// The token was used successfully to authenticate against the Git remote.
    case valid
    /// The token is not accessible due to permission issues.
    case permissionDenied
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .notFound: return 1
      case .invalid: return 2
      case .valid: return 3
      case .permissionDenied: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TOKEN_STATUS_UNSPECIFIED"
      case .notFound: return "NOT_FOUND"
      case .invalid: return "INVALID"
      case .valid: return "VALID"
      case .permissionDenied: return "PERMISSION_DENIED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TokenStatus/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TOKEN_STATUS_UNSPECIFIED": self = .unspecified
      case "NOT_FOUND": self = .notFound
      case "INVALID": self = .invalid
      case "VALID": self = .valid
      case "PERMISSION_DENIED": self = .permissionDenied
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TokenStatus/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .notFound
      case 2: self = .invalid
      case 3: self = .valid
      case 4: self = .permissionDenied
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .notFound: return try container.encode(1)
      case .invalid: return try container.encode(2)
      case .valid: return try container.encode(3)
      case .permissionDenied: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.ComputeRepositoryAccessTokenStatusResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
