// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol DataformStub {
    func getTeamFolder(
      request: GetTeamFolderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.TeamFolder

    func createTeamFolder(
      request: CreateTeamFolderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.TeamFolder

    func updateTeamFolder(
      request: UpdateTeamFolderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.TeamFolder

    func deleteTeamFolder(
      request: DeleteTeamFolderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func deleteTeamFolderTree(
      request: DeleteTeamFolderTreeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func queryTeamFolderContents(
      request: QueryTeamFolderContentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.QueryTeamFolderContentsResponse

    func searchTeamFolders(
      request: SearchTeamFoldersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.SearchTeamFoldersResponse

    func getFolder(
      request: GetFolderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.Folder

    func createFolder(
      request: CreateFolderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.Folder

    func updateFolder(
      request: UpdateFolderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.Folder

    func deleteFolder(
      request: DeleteFolderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func deleteFolderTree(
      request: DeleteFolderTreeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func queryFolderContents(
      request: QueryFolderContentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.QueryFolderContentsResponse

    func queryUserRootContents(
      request: QueryUserRootContentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.QueryUserRootContentsResponse

    func moveFolder(
      request: MoveFolderRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRepositories(
      request: ListRepositoriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ListRepositoriesResponse

    func getRepository(
      request: GetRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.Repository

    func createRepository(
      request: CreateRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.Repository

    func updateRepository(
      request: UpdateRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.Repository

    func deleteRepository(
      request: DeleteRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func moveRepository(
      request: MoveRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func commitRepositoryChanges(
      request: CommitRepositoryChangesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.CommitRepositoryChangesResponse

    func readRepositoryFile(
      request: ReadRepositoryFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ReadRepositoryFileResponse

    func queryRepositoryDirectoryContents(
      request: QueryRepositoryDirectoryContentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.QueryRepositoryDirectoryContentsResponse

    func fetchRepositoryHistory(
      request: FetchRepositoryHistoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.FetchRepositoryHistoryResponse

    func computeRepositoryAccessTokenStatus(
      request: ComputeRepositoryAccessTokenStatusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ComputeRepositoryAccessTokenStatusResponse

    func fetchRemoteBranches(
      request: FetchRemoteBranchesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.FetchRemoteBranchesResponse

    func listWorkspaces(
      request: ListWorkspacesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ListWorkspacesResponse

    func getWorkspace(
      request: GetWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.Workspace

    func createWorkspace(
      request: CreateWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.Workspace

    func deleteWorkspace(
      request: DeleteWorkspaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func installNpmPackages(
      request: InstallNpmPackagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.InstallNpmPackagesResponse

    func pullGitCommits(
      request: PullGitCommitsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.PullGitCommitsResponse

    func pushGitCommits(
      request: PushGitCommitsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.PushGitCommitsResponse

    func fetchFileGitStatuses(
      request: FetchFileGitStatusesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.FetchFileGitStatusesResponse

    func fetchGitAheadBehind(
      request: FetchGitAheadBehindRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.FetchGitAheadBehindResponse

    func commitWorkspaceChanges(
      request: CommitWorkspaceChangesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.CommitWorkspaceChangesResponse

    func resetWorkspaceChanges(
      request: ResetWorkspaceChangesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ResetWorkspaceChangesResponse

    func fetchFileDiff(
      request: FetchFileDiffRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.FetchFileDiffResponse

    func queryDirectoryContents(
      request: QueryDirectoryContentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.QueryDirectoryContentsResponse

    func searchFiles(
      request: SearchFilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.SearchFilesResponse

    func makeDirectory(
      request: MakeDirectoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.MakeDirectoryResponse

    func removeDirectory(
      request: RemoveDirectoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.RemoveDirectoryResponse

    func moveDirectory(
      request: MoveDirectoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.MoveDirectoryResponse

    func readFile(
      request: ReadFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ReadFileResponse

    func removeFile(
      request: RemoveFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.RemoveFileResponse

    func moveFile(
      request: MoveFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.MoveFileResponse

    func writeFile(
      request: WriteFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.WriteFileResponse

    func listReleaseConfigs(
      request: ListReleaseConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ListReleaseConfigsResponse

    func getReleaseConfig(
      request: GetReleaseConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ReleaseConfig

    func createReleaseConfig(
      request: CreateReleaseConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ReleaseConfig

    func updateReleaseConfig(
      request: UpdateReleaseConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ReleaseConfig

    func deleteReleaseConfig(
      request: DeleteReleaseConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listCompilationResults(
      request: ListCompilationResultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ListCompilationResultsResponse

    func getCompilationResult(
      request: GetCompilationResultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.CompilationResult

    func createCompilationResult(
      request: CreateCompilationResultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.CompilationResult

    func queryCompilationResultActions(
      request: QueryCompilationResultActionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.QueryCompilationResultActionsResponse

    func listWorkflowConfigs(
      request: ListWorkflowConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ListWorkflowConfigsResponse

    func getWorkflowConfig(
      request: GetWorkflowConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.WorkflowConfig

    func createWorkflowConfig(
      request: CreateWorkflowConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.WorkflowConfig

    func updateWorkflowConfig(
      request: UpdateWorkflowConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.WorkflowConfig

    func deleteWorkflowConfig(
      request: DeleteWorkflowConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listWorkflowInvocations(
      request: ListWorkflowInvocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.ListWorkflowInvocationsResponse

    func getWorkflowInvocation(
      request: GetWorkflowInvocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.WorkflowInvocation

    func createWorkflowInvocation(
      request: CreateWorkflowInvocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.WorkflowInvocation

    func deleteWorkflowInvocation(
      request: DeleteWorkflowInvocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelWorkflowInvocation(
      request: CancelWorkflowInvocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.CancelWorkflowInvocationResponse

    func queryWorkflowInvocationActions(
      request: QueryWorkflowInvocationActionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.QueryWorkflowInvocationActionsResponse

    func getConfig(
      request: GetConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.Config

    func updateConfig(
      request: UpdateConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataFormV1.Config

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
