// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// `DeleteFolderTree` request message.
public struct DeleteFolderTreeRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The Folder's name.
  /// Format: projects/{project}/locations/{location}/folders/{folder}
  public var name: Swift.String = Swift.String()

  /// Optional. If `false` (default): The operation will fail if any
  /// Repository within the folder hierarchy has associated Release Configs or
  /// Workflow Configs.
  ///
  /// If `true`: The operation will attempt to delete everything, including any
  /// Release Configs and Workflow Configs linked to Repositories within the
  /// folder hierarchy. This permanently removes schedules and resources.
  public var force: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `DeleteFolderTreeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteFolderTreeRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.dataform.v1.DeleteFolderTreeRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
