// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a single entry in a directory.
public struct DirectoryEntry: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Entry with metadata.
  public var metadata: FilesystemEntryMetadata? = nil

  /// The entry's contents.
  public var entry: OneOf_Entry? = nil

  /// Initialize a new instance of `DirectoryEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DirectoryEntry().with { $0.file = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case file = "file"
    case directory = "directory"
    case metadata = "metadata"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.metadata = try container.decodeIfPresent(FilesystemEntryMetadata.self, forKey: .metadata)

    var entry: OneOf_Entry? = nil
    let entryCheckAndSet = {
      if entry != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'entry'"))
      }
      entry = $0
    }
    if let file = try container.decodeIfPresent(Swift.String.self, forKey: .file) {
      try entryCheckAndSet(.file(file))
    }
    if let directory = try container.decodeIfPresent(Swift.String.self, forKey: .directory) {
      try entryCheckAndSet(.directory(directory))
    }
    self.entry = entry
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.metadata, forKey: .metadata)

    if let choice = self.entry {
      switch choice {
      case .file(let value):
        try container.encode(value, forKey: .file)
      case .directory(let value):
        try container.encode(value, forKey: .directory)
      }
    }
  }

  /// The entry's contents.
  public enum OneOf_Entry: Codable, Equatable, Sendable {
    /// A file in the directory.
    case file(Swift.String)
    /// A child directory in the directory.
    case directory(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.DirectoryEntry"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
