// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Metadata about a repository snapshot stored in Google Cloud Storage.
public struct GcsRepositorySnapshotMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The Google Cloud Storage URI of the repository snapshot.
  public var repositorySnapshotUri: Swift.String = Swift.String()

  /// Output only. The crc32c checksum of the repository snapshot, big-endian
  /// base64 encoded.
  public var crc32CChecksum: Swift.String = Swift.String()

  /// Output only. The generation number of the Cloud Storage object. See
  /// https://cloud.google.com/storage/docs/metadata#generation-number.
  public var generation: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `GcsRepositorySnapshotMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcsRepositorySnapshotMetadata().with { $0.repositorySnapshotUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case repositorySnapshotUri = "repositorySnapshotUri"
    case crc32CChecksum = "crc32cChecksum"
    case generation = "generation"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.repositorySnapshotUri = try container.decode(
      Swift.String.self, forKey: .repositorySnapshotUri)
    self.crc32CChecksum = try container.decode(Swift.String.self, forKey: .crc32CChecksum)
    self.generation = try container.decode(Swift.Int64.self, forKey: .generation)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.repositorySnapshotUri, forKey: .repositorySnapshotUri)
    try container.encode(self.crc32CChecksum, forKey: .crc32CChecksum)
    try container.encode(self.generation, forKey: .generation)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.GcsRepositorySnapshotMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
