// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Includes various configuration options for a workflow invocation.
/// If both `included_targets` and `included_tags` are unset, all actions
/// will be included.
public struct InvocationConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The set of action identifiers to include.
  public var includedTargets: [Target] = []

  /// Optional. The set of tags to include.
  public var includedTags: [Swift.String] = []

  /// Optional. When set to true, transitive dependencies of included actions
  /// will be executed.
  public var transitiveDependenciesIncluded: Swift.Bool = Swift.Bool()

  /// Optional. When set to true, transitive dependents of included actions will
  /// be executed.
  public var transitiveDependentsIncluded: Swift.Bool = Swift.Bool()

  /// Optional. When set to true, any incremental tables will be fully refreshed.
  public var fullyRefreshIncrementalTablesEnabled: Swift.Bool = Swift.Bool()

  /// Optional. The service account to run workflow invocations under.
  public var serviceAccount: Swift.String = Swift.String()

  /// Optional. Specifies the priority for query execution in BigQuery.
  /// More information can be found at
  /// https://cloud.google.com/bigquery/docs/running-queries#queries.
  public var queryPriority: InvocationConfig.QueryPriority? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InvocationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InvocationConfig().with { $0.includedTargets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let includedTargets = CodingKeys(stringValue: "includedTargets")
    static let includedTags = CodingKeys(stringValue: "includedTags")
    static let transitiveDependenciesIncluded = CodingKeys(
      stringValue: "transitiveDependenciesIncluded")
    static let transitiveDependentsIncluded = CodingKeys(
      stringValue: "transitiveDependentsIncluded")
    static let fullyRefreshIncrementalTablesEnabled = CodingKeys(
      stringValue: "fullyRefreshIncrementalTablesEnabled")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let queryPriority = CodingKeys(stringValue: "queryPriority")

    static let _knownKeys: Set<Swift.String> = [
      "includedTargets",
      "includedTags",
      "transitiveDependenciesIncluded",
      "transitiveDependentsIncluded",
      "fullyRefreshIncrementalTablesEnabled",
      "serviceAccount",
      "queryPriority",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Target].self, forKey: .includedTargets) {
      self.includedTargets = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .includedTags) {
      self.includedTags = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .transitiveDependenciesIncluded)
    {
      self.transitiveDependenciesIncluded = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .transitiveDependentsIncluded)
    {
      self.transitiveDependentsIncluded = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .fullyRefreshIncrementalTablesEnabled)
    {
      self.fullyRefreshIncrementalTablesEnabled = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    self.queryPriority = try container.decodeIfPresent(
      InvocationConfig.QueryPriority.self, forKey: .queryPriority)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.includedTargets, forKey: .includedTargets)
    try container.encode(self.includedTags, forKey: .includedTags)
    try container.encode(
      self.transitiveDependenciesIncluded, forKey: .transitiveDependenciesIncluded)
    try container.encode(self.transitiveDependentsIncluded, forKey: .transitiveDependentsIncluded)
    try container.encode(
      self.fullyRefreshIncrementalTablesEnabled, forKey: .fullyRefreshIncrementalTablesEnabled)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encodeIfPresent(self.queryPriority, forKey: .queryPriority)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Types of priority for query execution in BigQuery.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum QueryPriority: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Query will be executed in BigQuery with interactive priority.
    /// More information can be found at
    /// https://cloud.google.com/bigquery/docs/running-queries#queries.
    case interactive
    /// Query will be executed in BigQuery with batch priority.
    /// More information can be found at
    /// https://cloud.google.com/bigquery/docs/running-queries#batchqueries.
    case batch
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .interactive: return 1
      case .batch: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "QUERY_PRIORITY_UNSPECIFIED"
      case .interactive: return "INTERACTIVE"
      case .batch: return "BATCH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:QueryPriority/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "QUERY_PRIORITY_UNSPECIFIED": self = .unspecified
      case "INTERACTIVE": self = .interactive
      case "BATCH": self = .batch
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:QueryPriority/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .interactive
      case 2: self = .batch
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("QUERY_PRIORITY_UNSPECIFIED")
      case .interactive: return try container.encode("INTERACTIVE")
      case .batch: return try container.encode("BATCH")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.InvocationConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
