// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// `ListCompilationResults` request message.
public struct ListCompilationResultsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The repository in which to list compilation results. Must be in
  /// the format `projects/*/locations/*/repositories/*`.
  public var parent: Swift.String = Swift.String()

  /// Optional. Maximum number of compilation results to return. The server may
  /// return fewer items than requested. If unspecified, the server will pick an
  /// appropriate default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. Page token received from a previous `ListCompilationResults`
  /// call. Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to `ListCompilationResults`,
  /// with the exception of `page_size`, must match the call that provided the
  /// page token.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. This field only supports ordering by `name` and `create_time`.
  /// If unspecified, the server will choose the ordering.
  /// If specified, the default order is ascending for the `name` field.
  public var orderBy: Swift.String = Swift.String()

  /// Optional. Filter for the returned list.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListCompilationResultsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCompilationResultsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.ListCompilationResultsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
