// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Configures various aspects of Dataform notebook runtime.
public struct NotebookRuntimeOptions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The resource name of the [Colab runtime template]
  /// (https://cloud.google.com/colab/docs/runtimes), from which a runtime is
  /// created for notebook executions. If not specified, a runtime is created
  /// with Colab's default specifications.
  public var aiPlatformNotebookRuntimeTemplate: Swift.String = Swift.String()

  /// The location to store the notebook execution result.
  public var executionSink: OneOf_ExecutionSink? = nil

  /// The destination of the snapshot of repository files to be available for
  /// read-only access inside a notebook runtime
  public var repositorySnapshotStorage: OneOf_RepositorySnapshotStorage? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NotebookRuntimeOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NotebookRuntimeOptions().with { $0.gcsOutputBucket = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcsOutputBucket = CodingKeys(stringValue: "gcsOutputBucket")
    static let gcsRepositorySnapshotDestination = CodingKeys(
      stringValue: "gcsRepositorySnapshotDestination")
    static let aiPlatformNotebookRuntimeTemplate = CodingKeys(
      stringValue: "aiPlatformNotebookRuntimeTemplate")

    static let _knownKeys: Set<Swift.String> = [
      "gcsOutputBucket",
      "gcsRepositorySnapshotDestination",
      "aiPlatformNotebookRuntimeTemplate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .aiPlatformNotebookRuntimeTemplate)
    {
      self.aiPlatformNotebookRuntimeTemplate = value
    }

    var executionSink: OneOf_ExecutionSink? = nil
    let executionSinkCheckAndSet = {
      if executionSink != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'executionSink'"))
      }
      executionSink = $0
    }
    if let gcsOutputBucket = try container.decodeIfPresent(
      Swift.String.self, forKey: .gcsOutputBucket)
    {
      try executionSinkCheckAndSet(.gcsOutputBucket(gcsOutputBucket))
    }
    self.executionSink = executionSink

    var repositorySnapshotStorage: OneOf_RepositorySnapshotStorage? = nil
    let repositorySnapshotStorageCheckAndSet = {
      if repositorySnapshotStorage != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'repositorySnapshotStorage'"))
      }
      repositorySnapshotStorage = $0
    }
    if let gcsRepositorySnapshotDestination = try container.decodeIfPresent(
      GcsRepositorySnapshotDestination?.self, forKey: .gcsRepositorySnapshotDestination)
    {
      try repositorySnapshotStorageCheckAndSet(
        .gcsRepositorySnapshotDestination(gcsRepositorySnapshotDestination))
    }
    self.repositorySnapshotStorage = repositorySnapshotStorage
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(
      self.aiPlatformNotebookRuntimeTemplate, forKey: .aiPlatformNotebookRuntimeTemplate)

    if let choice = self.executionSink {
      switch choice {
      case .gcsOutputBucket(let value):
        try container.encode(value, forKey: .gcsOutputBucket)
      }
    }

    if let choice = self.repositorySnapshotStorage {
      switch choice {
      case .gcsRepositorySnapshotDestination(let value):
        try container.encode(value, forKey: .gcsRepositorySnapshotDestination)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The location to store the notebook execution result.
  public enum OneOf_ExecutionSink: Codable, Equatable, Sendable {
    /// Optional. The Google Cloud Storage location to upload the result to.
    /// Format: `gs://bucket-name`.
    case gcsOutputBucket(Swift.String)
  }

  /// The destination of the snapshot of repository files to be available for
  /// read-only access inside a notebook runtime
  public enum OneOf_RepositorySnapshotStorage: Codable, Equatable, Sendable {
    /// Optional. The Google Cloud Storage destination to upload the snapshot to.
    /// For empty URI it defaults to the provided gcs_output_bucket.
    /// Format: `gs://bucket-name/path/`.
    indirect case gcsRepositorySnapshotDestination(GcsRepositorySnapshotDestination?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.NotebookRuntimeOptions"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
