// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Configures various aspects of Dataform notebook runtime.
public struct NotebookRuntimeOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The resource name of the [Colab runtime template]
  /// (https://cloud.google.com/colab/docs/runtimes), from which a runtime is
  /// created for notebook executions. If not specified, a runtime is created
  /// with Colab's default specifications.
  public var aiPlatformNotebookRuntimeTemplate: Swift.String = Swift.String()

  /// The location to store the notebook execution result.
  public var executionSink: OneOf_ExecutionSink? = nil

  /// Initialize a new instance of `NotebookRuntimeOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NotebookRuntimeOptions().with { $0.gcsOutputBucket = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case gcsOutputBucket = "gcsOutputBucket"
    case aiPlatformNotebookRuntimeTemplate = "aiPlatformNotebookRuntimeTemplate"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.aiPlatformNotebookRuntimeTemplate = try container.decode(
      Swift.String.self, forKey: .aiPlatformNotebookRuntimeTemplate)

    var executionSink: OneOf_ExecutionSink? = nil
    let executionSinkCheckAndSet = {
      if executionSink != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'executionSink'"))
      }
      executionSink = $0
    }
    if let gcsOutputBucket = try container.decodeIfPresent(
      Swift.String.self, forKey: .gcsOutputBucket)
    {
      try executionSinkCheckAndSet(.gcsOutputBucket(gcsOutputBucket))
    }
    self.executionSink = executionSink
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(
      self.aiPlatformNotebookRuntimeTemplate, forKey: .aiPlatformNotebookRuntimeTemplate)

    if let choice = self.executionSink {
      switch choice {
      case .gcsOutputBucket(let value):
        try container.encode(value, forKey: .gcsOutputBucket)
      }
    }
  }

  /// The location to store the notebook execution result.
  public enum OneOf_ExecutionSink: Codable, Equatable, Sendable {
    /// Optional. The Google Cloud Storage location to upload the result to.
    /// Format: `gs://bucket-name`.
    case gcsOutputBucket(Swift.String)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.dataform.v1.NotebookRuntimeOptions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
