// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describes a relation and its columns.
public struct RelationDescriptor: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A text description of the relation.
  public var description: Swift.String = Swift.String()

  /// A list of descriptions of columns within the relation.
  public var columns: [RelationDescriptor.ColumnDescriptor] = []

  /// A set of BigQuery labels that should be applied to the relation.
  public var bigqueryLabels: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `RelationDescriptor`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RelationDescriptor().with { $0.description = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Describes a column.
  public struct ColumnDescriptor: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The identifier for the column. Each entry in `path` represents one level
    /// of nesting.
    public var path: [Swift.String] = []

    /// A textual description of the column.
    public var description: Swift.String = Swift.String()

    /// A list of BigQuery policy tags that will be applied to the column.
    public var bigqueryPolicyTags: [Swift.String] = []

    /// Initialize a new instance of `ColumnDescriptor`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ColumnDescriptor().with { $0.path = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.dataform.v1.RelationDescriptor.ColumnDescriptor"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.dataform.v1.RelationDescriptor"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
