// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// Represents a Dataform release configuration.
public struct ReleaseConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The release config's name.
  public var name: Swift.String = Swift.String()

  /// Required. Git commit/tag/branch name at which the repository should be
  /// compiled. Must exist in the remote repository. Examples:
  /// - a commit SHA: `12ade345`
  /// - a tag: `tag1`
  /// - a branch name: `branch1`
  public var gitCommitish: Swift.String = Swift.String()

  /// Optional. If set, fields of `code_compilation_config` override the default
  /// compilation settings that are specified in dataform.json.
  public var codeCompilationConfig: CodeCompilationConfig? = nil

  /// Optional. Optional schedule (in cron format) for automatic creation of
  /// compilation results.
  public var cronSchedule: Swift.String = Swift.String()

  /// Optional. Specifies the time zone to be used when interpreting
  /// cron_schedule. Must be a time zone name from the time zone database
  /// (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). If left
  /// unspecified, the default is UTC.
  public var timeZone: Swift.String = Swift.String()

  /// Output only. Records of the 10 most recent scheduled release attempts,
  /// ordered in descending order of `release_time`. Updated whenever automatic
  /// creation of a compilation result is triggered by cron_schedule.
  public var recentScheduledReleaseRecords: [ReleaseConfig.ScheduledReleaseRecord] = []

  /// Optional. The name of the currently released compilation result for this
  /// release config. This value is updated when a compilation result is
  /// automatically created from this release config (using cron_schedule), or
  /// when this resource is updated by API call (perhaps to roll back to an
  /// earlier release). The compilation result must have been created using this
  /// release config. Must be in the format
  /// `projects/*/locations/*/repositories/*/compilationResults/*`.
  public var releaseCompilationResult: Swift.String = Swift.String()

  /// Optional. Disables automatic creation of compilation results.
  public var disabled: Swift.Bool = Swift.Bool()

  /// Output only. All the metadata information that is used internally to serve
  /// the resource. For example: timestamps, flags, status fields, etc. The
  /// format of this field is a JSON string.
  public var internalMetadata: Swift.String? = nil

  /// Initialize a new instance of `ReleaseConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReleaseConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A record of an attempt to create a compilation result for this release
  /// config.
  public struct ScheduledReleaseRecord: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The timestamp of this release attempt.
    public var releaseTime: GoogleCloudWkt.Timestamp? = nil

    /// The result of this release attempt.
    public var result: OneOf_Result? = nil

    /// Initialize a new instance of `ScheduledReleaseRecord`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ScheduledReleaseRecord().with { $0.compilationResult = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case compilationResult = "compilationResult"
      case errorStatus = "errorStatus"
      case releaseTime = "releaseTime"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.releaseTime = try container.decodeIfPresent(
        GoogleCloudWkt.Timestamp.self, forKey: .releaseTime)

      var result: OneOf_Result? = nil
      let resultCheckAndSet = {
        if result != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'result'"))
        }
        result = $0
      }
      if let compilationResult = try container.decodeIfPresent(
        Swift.String.self, forKey: .compilationResult)
      {
        try resultCheckAndSet(.compilationResult(compilationResult))
      }
      if let errorStatus = try container.decodeIfPresent(
        GoogleRpc.Status?.self, forKey: .errorStatus)
      {
        try resultCheckAndSet(.errorStatus(errorStatus))
      }
      self.result = result
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.releaseTime, forKey: .releaseTime)

      if let choice = self.result {
        switch choice {
        case .compilationResult(let value):
          try container.encode(value, forKey: .compilationResult)
        case .errorStatus(let value):
          try container.encode(value, forKey: .errorStatus)
        }
      }
    }

    /// The result of this release attempt.
    public enum OneOf_Result: Codable, Equatable, Sendable {
      /// The name of the created compilation result, if one was successfully
      /// created. Must be in the format
      /// `projects/*/locations/*/repositories/*/compilationResults/*`.
      case compilationResult(Swift.String)
      /// The error status encountered upon this attempt to create the
      /// compilation result, if the attempt was unsuccessful.
      indirect case errorStatus(GoogleRpc.Status?)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.dataform.v1.ReleaseConfig.ScheduledReleaseRecord"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.dataform.v1.ReleaseConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
