// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents a Dataform Git repository.
public struct Repository: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The repository's name.
  public var name: Swift.String = Swift.String()

  /// Optional. The name of the containing folder of the repository.
  /// The field is immutable and it can be modified via a MoveRepository
  /// operation.
  /// Format: `projects/*/locations/*/folders/*`. or
  /// `projects/*/locations/*/teamFolders/*`.
  public var containingFolder: Swift.String? = nil

  /// Output only. The resource name of the TeamFolder that this Repository is
  /// associated with. This should take the format:
  /// projects/{project}/locations/{location}/teamFolders/{teamFolder}. If this
  /// is not set, the Repository is not associated with a TeamFolder.
  public var teamFolderName: Swift.String? = nil

  /// Output only. The timestamp of when the repository was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. The repository's user-friendly name.
  public var displayName: Swift.String = Swift.String()

  /// Optional. If set, configures this repository to be linked to a Git remote.
  public var gitRemoteSettings: Repository.GitRemoteSettings? = nil

  /// Optional. The name of the Secret Manager secret version to be used to
  /// interpolate variables into the .npmrc file for package installation
  /// operations. Must be in the format `projects/*/secrets/*/versions/*`. The
  /// file itself must be in a JSON format.
  public var npmrcEnvironmentVariablesSecretVersion: Swift.String = Swift.String()

  /// Optional. If set, fields of `workspace_compilation_overrides` override the
  /// default compilation settings that are specified in dataform.json when
  /// creating workspace-scoped compilation results. See documentation for
  /// `WorkspaceCompilationOverrides` for more information.
  public var workspaceCompilationOverrides: Repository.WorkspaceCompilationOverrides? = nil

  /// Optional. Repository user labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Input only. If set to true, the authenticated user will be
  /// granted the roles/dataform.admin role on the created repository.
  public var setAuthenticatedUserAdmin: Swift.Bool = Swift.Bool()

  /// Optional. The service account to run workflow invocations under.
  public var serviceAccount: Swift.String = Swift.String()

  /// Optional. The reference to a KMS encryption key. If provided, it will be
  /// used to encrypt user data in the repository and all child resources. It is
  /// not possible to add or update the encryption key after the repository is
  /// created. Example:
  /// `projects/{kms_project}/locations/{location}/keyRings/{key_location}/cryptoKeys/{key}`
  public var kmsKeyName: Swift.String = Swift.String()

  /// Output only. A data encryption state of a Git repository if this Repository
  /// is protected by a KMS key.
  public var dataEncryptionState: DataEncryptionState? = nil

  /// Output only. All the metadata information that is used internally to serve
  /// the resource. For example: timestamps, flags, status fields, etc. The
  /// format of this field is a JSON string.
  public var internalMetadata: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Repository`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Repository().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let containingFolder = CodingKeys(stringValue: "containingFolder")
    static let teamFolderName = CodingKeys(stringValue: "teamFolderName")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let gitRemoteSettings = CodingKeys(stringValue: "gitRemoteSettings")
    static let npmrcEnvironmentVariablesSecretVersion = CodingKeys(
      stringValue: "npmrcEnvironmentVariablesSecretVersion")
    static let workspaceCompilationOverrides = CodingKeys(
      stringValue: "workspaceCompilationOverrides")
    static let labels = CodingKeys(stringValue: "labels")
    static let setAuthenticatedUserAdmin = CodingKeys(stringValue: "setAuthenticatedUserAdmin")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let kmsKeyName = CodingKeys(stringValue: "kmsKeyName")
    static let dataEncryptionState = CodingKeys(stringValue: "dataEncryptionState")
    static let internalMetadata = CodingKeys(stringValue: "internalMetadata")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "containingFolder",
      "teamFolderName",
      "createTime",
      "displayName",
      "gitRemoteSettings",
      "npmrcEnvironmentVariablesSecretVersion",
      "workspaceCompilationOverrides",
      "labels",
      "setAuthenticatedUserAdmin",
      "serviceAccount",
      "kmsKeyName",
      "dataEncryptionState",
      "internalMetadata",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.containingFolder = try container.decodeIfPresent(
      Swift.String.self, forKey: .containingFolder)
    self.teamFolderName = try container.decodeIfPresent(Swift.String.self, forKey: .teamFolderName)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    self.gitRemoteSettings = try container.decodeIfPresent(
      Repository.GitRemoteSettings.self, forKey: .gitRemoteSettings)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .npmrcEnvironmentVariablesSecretVersion)
    {
      self.npmrcEnvironmentVariablesSecretVersion = value
    }
    self.workspaceCompilationOverrides = try container.decodeIfPresent(
      Repository.WorkspaceCompilationOverrides.self, forKey: .workspaceCompilationOverrides)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .setAuthenticatedUserAdmin)
    {
      self.setAuthenticatedUserAdmin = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKeyName) {
      self.kmsKeyName = value
    }
    self.dataEncryptionState = try container.decodeIfPresent(
      DataEncryptionState.self, forKey: .dataEncryptionState)
    self.internalMetadata = try container.decodeIfPresent(
      Swift.String.self, forKey: .internalMetadata)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.containingFolder, forKey: .containingFolder)
    try container.encodeIfPresent(self.teamFolderName, forKey: .teamFolderName)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encodeIfPresent(self.gitRemoteSettings, forKey: .gitRemoteSettings)
    try container.encode(
      self.npmrcEnvironmentVariablesSecretVersion, forKey: .npmrcEnvironmentVariablesSecretVersion)
    try container.encodeIfPresent(
      self.workspaceCompilationOverrides, forKey: .workspaceCompilationOverrides)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.setAuthenticatedUserAdmin, forKey: .setAuthenticatedUserAdmin)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.kmsKeyName, forKey: .kmsKeyName)
    try container.encodeIfPresent(self.dataEncryptionState, forKey: .dataEncryptionState)
    try container.encodeIfPresent(self.internalMetadata, forKey: .internalMetadata)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Controls Git remote configuration for a repository.
  public struct GitRemoteSettings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The Git remote's URL.
    public var url: Swift.String = Swift.String()

    /// Optional. The Git remote's default branch name.
    /// If not set, `main` will be used.
    public var defaultBranch: Swift.String = Swift.String()

    /// Output only. The Git remote's effective default branch name.
    /// This is the default branch name of the Git remote if it is set,
    /// otherwise it is `main`.
    public var effectiveDefaultBranch: Swift.String = Swift.String()

    /// Optional. The name of the Secret Manager secret version to use as an
    /// authentication token for Git operations. Must be in the format
    /// `projects/*/secrets/*/versions/*`.
    public var authenticationTokenSecretVersion: Swift.String = Swift.String()

    /// Optional. Authentication fields for remote uris using SSH protocol.
    public var sshAuthenticationConfig: Repository.GitRemoteSettings.SshAuthenticationConfig? = nil

    /// Optional. Resource name for the `GitRepositoryLink` used for machine
    /// credentials. Must be in the format
    /// `projects/*/locations/*/connections/*/gitRepositoryLinks/*`
    public var gitRepositoryLink: Swift.String? = nil

    /// Output only. Deprecated: The field does not contain any token status
    /// information.
    @available(*, deprecated)
    public var tokenStatus: Repository.GitRemoteSettings.TokenStatus = Repository.GitRemoteSettings
      .TokenStatus()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `GitRemoteSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GitRemoteSettings().with { $0.url = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let url = CodingKeys(stringValue: "url")
      static let defaultBranch = CodingKeys(stringValue: "defaultBranch")
      static let effectiveDefaultBranch = CodingKeys(stringValue: "effectiveDefaultBranch")
      static let authenticationTokenSecretVersion = CodingKeys(
        stringValue: "authenticationTokenSecretVersion")
      static let sshAuthenticationConfig = CodingKeys(stringValue: "sshAuthenticationConfig")
      static let gitRepositoryLink = CodingKeys(stringValue: "gitRepositoryLink")
      static let tokenStatus = CodingKeys(stringValue: "tokenStatus")

      static let _knownKeys: Set<Swift.String> = [
        "url",
        "defaultBranch",
        "effectiveDefaultBranch",
        "authenticationTokenSecretVersion",
        "sshAuthenticationConfig",
        "gitRepositoryLink",
        "tokenStatus",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .url) {
        self.url = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .defaultBranch) {
        self.defaultBranch = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .effectiveDefaultBranch)
      {
        self.effectiveDefaultBranch = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .authenticationTokenSecretVersion)
      {
        self.authenticationTokenSecretVersion = value
      }
      self.sshAuthenticationConfig = try container.decodeIfPresent(
        Repository.GitRemoteSettings.SshAuthenticationConfig.self, forKey: .sshAuthenticationConfig)
      self.gitRepositoryLink = try container.decodeIfPresent(
        Swift.String.self, forKey: .gitRepositoryLink)
      if let value = try container.decodeIfPresent(
        Repository.GitRemoteSettings.TokenStatus.self, forKey: .tokenStatus)
      {
        self.tokenStatus = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.url, forKey: .url)
      try container.encode(self.defaultBranch, forKey: .defaultBranch)
      try container.encode(self.effectiveDefaultBranch, forKey: .effectiveDefaultBranch)
      try container.encode(
        self.authenticationTokenSecretVersion, forKey: .authenticationTokenSecretVersion)
      try container.encodeIfPresent(self.sshAuthenticationConfig, forKey: .sshAuthenticationConfig)
      try container.encodeIfPresent(self.gitRepositoryLink, forKey: .gitRepositoryLink)
      try container.encode(self.tokenStatus, forKey: .tokenStatus)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Configures fields for performing SSH authentication.
    public struct SshAuthenticationConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Required. The name of the Secret Manager secret version to use as a
      /// ssh private key for Git operations.
      /// Must be in the format `projects/*/secrets/*/versions/*`.
      public var userPrivateKeySecretVersion: Swift.String = Swift.String()

      /// Required. Content of a public SSH key to verify an identity of a remote
      /// Git host.
      public var hostPublicKey: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

      /// Initialize a new instance of `SshAuthenticationConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = SshAuthenticationConfig().with { $0.userPrivateKeySecretVersion = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let userPrivateKeySecretVersion = CodingKeys(
          stringValue: "userPrivateKeySecretVersion")
        static let hostPublicKey = CodingKeys(stringValue: "hostPublicKey")

        static let _knownKeys: Set<Swift.String> = [
          "userPrivateKeySecretVersion",
          "hostPublicKey",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(
          Swift.String.self, forKey: .userPrivateKeySecretVersion)
        {
          self.userPrivateKeySecretVersion = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostPublicKey) {
          self.hostPublicKey = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleCloudWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.userPrivateKeySecretVersion, forKey: .userPrivateKeySecretVersion)
        try container.encode(self.hostPublicKey, forKey: .hostPublicKey)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dataform.v1.Repository.GitRemoteSettings.SshAuthenticationConfig"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// The status of the authentication token.
    public enum TokenStatus: Codable, Equatable, Sendable {
      /// Default value. This value is unused.
      case unspecified
      /// The token could not be found in Secret Manager (or the Dataform
      /// Service Account did not have permission to access it).
      case notFound
      /// The token could not be used to authenticate against the Git remote.
      case invalid
      /// The token was used successfully to authenticate against the Git remote.
      case valid
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .notFound: return 1
        case .invalid: return 2
        case .valid: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TOKEN_STATUS_UNSPECIFIED"
        case .notFound: return "NOT_FOUND"
        case .invalid: return "INVALID"
        case .valid: return "VALID"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TokenStatus/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TOKEN_STATUS_UNSPECIFIED": self = .unspecified
        case "NOT_FOUND": self = .notFound
        case "INVALID": self = .invalid
        case "VALID": self = .valid
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TokenStatus/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .notFound
        case 2: self = .invalid
        case 3: self = .valid
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("TOKEN_STATUS_UNSPECIFIED")
        case .notFound: return try container.encode("NOT_FOUND")
        case .invalid: return try container.encode("INVALID")
        case .valid: return try container.encode("VALID")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataform.v1.Repository.GitRemoteSettings"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configures workspace compilation overrides for a repository.
  public struct WorkspaceCompilationOverrides: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. The default database (Google Cloud project ID).
    public var defaultDatabase: Swift.String = Swift.String()

    /// Optional. The suffix that should be appended to all schema (BigQuery
    /// dataset ID) names.
    public var schemaSuffix: Swift.String = Swift.String()

    /// Optional. The prefix that should be prepended to all table names.
    public var tablePrefix: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `WorkspaceCompilationOverrides`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WorkspaceCompilationOverrides().with { $0.defaultDatabase = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let defaultDatabase = CodingKeys(stringValue: "defaultDatabase")
      static let schemaSuffix = CodingKeys(stringValue: "schemaSuffix")
      static let tablePrefix = CodingKeys(stringValue: "tablePrefix")

      static let _knownKeys: Set<Swift.String> = [
        "defaultDatabase",
        "schemaSuffix",
        "tablePrefix",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .defaultDatabase) {
        self.defaultDatabase = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .schemaSuffix) {
        self.schemaSuffix = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tablePrefix) {
        self.tablePrefix = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.defaultDatabase, forKey: .defaultDatabase)
      try container.encode(self.schemaSuffix, forKey: .schemaSuffix)
      try container.encode(self.tablePrefix, forKey: .tablePrefix)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataform.v1.Repository.WorkspaceCompilationOverrides"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.Repository"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
