// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// `SearchTeamFolders` request message.
public struct SearchTeamFoldersRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Location in which to query TeamFolders.
  /// Format: `projects/*/locations/*`.
  public var location: Swift.String = Swift.String()

  /// Optional. Maximum number of `TeamFolders` to return. The server may return
  /// fewer items than requested. If unspecified, the server will pick a default
  /// of `page_size` = 50.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. Page token received from a previous `SearchTeamFolders` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// `SearchTeamFolders`, with the exception of `page_size`, must
  /// match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Field to additionally sort results by.
  /// Supported keywords: `display_name` (default), `create_time`,
  /// `last_modified_time`. Examples:
  ///
  /// * `orderBy="display_name"`
  /// * `orderBy="display_name desc"`
  public var orderBy: Swift.String = Swift.String()

  /// Optional. Optional filtering for the returned list. Filtering is currently
  /// only supported on the `display_name` field.
  ///
  /// Example:
  ///
  /// * `filter="display_name="MyFolder""`
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `SearchTeamFoldersRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchTeamFoldersRequest().with { $0.location = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.SearchTeamFoldersRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
