// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a Dataform Git workspace.
public struct Workspace: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The workspace's name.
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp of when the workspace was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. A data encryption state of a Git repository if this Workspace
  /// is protected by a KMS key.
  public var dataEncryptionState: DataEncryptionState? = nil

  /// Output only. All the metadata information that is used internally to serve
  /// the resource. For example: timestamps, flags, status fields, etc. The
  /// format of this field is a JSON string.
  public var internalMetadata: Swift.String? = nil

  /// Optional. If set to true, workspaces will not be moved if its linked
  /// Repository is moved. Instead, it will be deleted.
  public var disableMoves: Swift.Bool? = nil

  /// Output only. Metadata indicating whether this resource is user-scoped. For
  /// `Workspace` resources, the `user_scoped` field is always `true`.
  public var privateResourceMetadata: PrivateResourceMetadata? = nil

  /// Initialize a new instance of `Workspace`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Workspace().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.dataform.v1.Workspace"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
