// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// Represents a single invocation of a compilation result.
public struct WorkflowInvocation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The workflow invocation's name.
  public var name: Swift.String = Swift.String()

  /// Immutable. If left unset, a default InvocationConfig will be used.
  public var invocationConfig: InvocationConfig? = nil

  /// Output only. This workflow invocation's current state.
  public var state: WorkflowInvocation.State = WorkflowInvocation.State()

  /// Output only. This workflow invocation's timing details.
  public var invocationTiming: GoogleType.Interval? = nil

  /// Output only. The resolved compilation result that was used to create this
  /// invocation. Will be in the format
  /// `projects/*/locations/*/repositories/*/compilationResults/*`.
  public var resolvedCompilationResult: Swift.String = Swift.String()

  /// Output only. Only set if the repository has a KMS Key.
  public var dataEncryptionState: DataEncryptionState? = nil

  /// Output only. All the metadata information that is used internally to serve
  /// the resource. For example: timestamps, flags, status fields, etc. The
  /// format of this field is a JSON string.
  public var internalMetadata: Swift.String? = nil

  /// Output only. Metadata indicating whether this resource is user-scoped.
  /// `WorkflowInvocation` resource is `user_scoped` only if it is sourced
  /// from a compilation result and the compilation result is user-scoped.
  public var privateResourceMetadata: PrivateResourceMetadata? = nil

  /// The source of the compilation result to use for this invocation.
  public var compilationSource: OneOf_CompilationSource? = nil

  /// Initialize a new instance of `WorkflowInvocation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WorkflowInvocation().with { $0.compilationResult = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case compilationResult = "compilationResult"
    case workflowConfig = "workflowConfig"
    case name = "name"
    case invocationConfig = "invocationConfig"
    case state = "state"
    case invocationTiming = "invocationTiming"
    case resolvedCompilationResult = "resolvedCompilationResult"
    case dataEncryptionState = "dataEncryptionState"
    case internalMetadata = "internalMetadata"
    case privateResourceMetadata = "privateResourceMetadata"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.invocationConfig = try container.decodeIfPresent(
      InvocationConfig.self, forKey: .invocationConfig)
    self.state = try container.decode(WorkflowInvocation.State.self, forKey: .state)
    self.invocationTiming = try container.decodeIfPresent(
      GoogleType.Interval.self, forKey: .invocationTiming)
    self.resolvedCompilationResult = try container.decode(
      Swift.String.self, forKey: .resolvedCompilationResult)
    self.dataEncryptionState = try container.decodeIfPresent(
      DataEncryptionState.self, forKey: .dataEncryptionState)
    self.internalMetadata = try container.decodeIfPresent(
      Swift.String.self, forKey: .internalMetadata)
    self.privateResourceMetadata = try container.decodeIfPresent(
      PrivateResourceMetadata.self, forKey: .privateResourceMetadata)

    var compilationSource: OneOf_CompilationSource? = nil
    let compilationSourceCheckAndSet = {
      if compilationSource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'compilationSource'"))
      }
      compilationSource = $0
    }
    if let compilationResult = try container.decodeIfPresent(
      Swift.String.self, forKey: .compilationResult)
    {
      try compilationSourceCheckAndSet(.compilationResult(compilationResult))
    }
    if let workflowConfig = try container.decodeIfPresent(
      Swift.String.self, forKey: .workflowConfig)
    {
      try compilationSourceCheckAndSet(.workflowConfig(workflowConfig))
    }
    self.compilationSource = compilationSource
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.invocationConfig, forKey: .invocationConfig)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.invocationTiming, forKey: .invocationTiming)
    try container.encode(self.resolvedCompilationResult, forKey: .resolvedCompilationResult)
    try container.encode(self.dataEncryptionState, forKey: .dataEncryptionState)
    try container.encode(self.internalMetadata, forKey: .internalMetadata)
    try container.encode(self.privateResourceMetadata, forKey: .privateResourceMetadata)

    if let choice = self.compilationSource {
      switch choice {
      case .compilationResult(let value):
        try container.encode(value, forKey: .compilationResult)
      case .workflowConfig(let value):
        try container.encode(value, forKey: .workflowConfig)
      }
    }
  }

  /// Represents the current state of a workflow invocation.
  public enum State: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// The workflow invocation is currently running.
    case running
    /// The workflow invocation succeeded. A terminal state.
    case succeeded
    /// The workflow invocation was cancelled. A terminal state.
    case cancelled
    /// The workflow invocation failed. A terminal state.
    case failed
    /// The workflow invocation is being cancelled, but some actions are still
    /// running.
    case canceling
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .running: return 1
      case .succeeded: return 2
      case .cancelled: return 3
      case .failed: return 4
      case .canceling: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .running: return "RUNNING"
      case .succeeded: return "SUCCEEDED"
      case .cancelled: return "CANCELLED"
      case .failed: return "FAILED"
      case .canceling: return "CANCELING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "RUNNING": self = .running
      case "SUCCEEDED": self = .succeeded
      case "CANCELLED": self = .cancelled
      case "FAILED": self = .failed
      case "CANCELING": self = .canceling
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .running
      case 2: self = .succeeded
      case 3: self = .cancelled
      case 4: self = .failed
      case 5: self = .canceling
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .running: return try container.encode(1)
      case .succeeded: return try container.encode(2)
      case .cancelled: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .canceling: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The source of the compilation result to use for this invocation.
  public enum OneOf_CompilationSource: Codable, Equatable, Sendable {
    /// Immutable. The name of the compilation result to use for this invocation.
    /// Must be in the format
    /// `projects/*/locations/*/repositories/*/compilationResults/*`.
    case compilationResult(Swift.String)
    /// Immutable. The name of the workflow config to invoke. Must be in the
    /// format `projects/*/locations/*/repositories/*/workflowConfigs/*`.
    case workflowConfig(Swift.String)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.dataform.v1.WorkflowInvocation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
