// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// Represents a Dataform workflow configuration.
public struct WorkflowConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The workflow config's name.
  public var name: Swift.String = Swift.String()

  /// Required. The name of the release config whose release_compilation_result
  /// should be executed. Must be in the format
  /// `projects/*/locations/*/repositories/*/releaseConfigs/*`.
  public var releaseConfig: Swift.String = Swift.String()

  /// Optional. If left unset, a default InvocationConfig will be used.
  public var invocationConfig: InvocationConfig? = nil

  /// Optional. Optional schedule (in cron format) for automatic execution of
  /// this workflow config.
  public var cronSchedule: Swift.String = Swift.String()

  /// Optional. Specifies the time zone to be used when interpreting
  /// cron_schedule. Must be a time zone name from the [time zone
  /// database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). If
  /// left unspecified, the default is `UTC`.
  public var timeZone: Swift.String = Swift.String()

  /// Output only. Records of the 10 most recent scheduled execution attempts,
  /// ordered in descending order of `execution_time`. Updated whenever automatic
  /// creation of a workflow invocation is triggered by cron_schedule.
  public var recentScheduledExecutionRecords: [WorkflowConfig.ScheduledExecutionRecord] = []

  /// Optional. Disables automatic creation of workflow invocations.
  public var disabled: Swift.Bool = Swift.Bool()

  /// Output only. The timestamp of when the WorkflowConfig was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp of when the WorkflowConfig was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. All the metadata information that is used internally to serve
  /// the resource. For example: timestamps, flags, status fields, etc. The
  /// format of this field is a JSON string.
  public var internalMetadata: Swift.String? = nil

  /// Initialize a new instance of `WorkflowConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WorkflowConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A record of an attempt to create a workflow invocation for this workflow
  /// config.
  public struct ScheduledExecutionRecord: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The timestamp of this execution attempt.
    public var executionTime: GoogleCloudWkt.Timestamp? = nil

    /// The result of this execution attempt.
    public var result: OneOf_Result? = nil

    /// Initialize a new instance of `ScheduledExecutionRecord`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ScheduledExecutionRecord().with { $0.workflowInvocation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case workflowInvocation = "workflowInvocation"
      case errorStatus = "errorStatus"
      case executionTime = "executionTime"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.executionTime = try container.decodeIfPresent(
        GoogleCloudWkt.Timestamp.self, forKey: .executionTime)

      var result: OneOf_Result? = nil
      let resultCheckAndSet = {
        if result != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'result'"))
        }
        result = $0
      }
      if let workflowInvocation = try container.decodeIfPresent(
        Swift.String.self, forKey: .workflowInvocation)
      {
        try resultCheckAndSet(.workflowInvocation(workflowInvocation))
      }
      if let errorStatus = try container.decodeIfPresent(
        GoogleRpc.Status?.self, forKey: .errorStatus)
      {
        try resultCheckAndSet(.errorStatus(errorStatus))
      }
      self.result = result
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.executionTime, forKey: .executionTime)

      if let choice = self.result {
        switch choice {
        case .workflowInvocation(let value):
          try container.encode(value, forKey: .workflowInvocation)
        case .errorStatus(let value):
          try container.encode(value, forKey: .errorStatus)
        }
      }
    }

    /// The result of this execution attempt.
    public enum OneOf_Result: Codable, Equatable, Sendable {
      /// The name of the created workflow invocation, if one was successfully
      /// created. Must be in the format
      /// `projects/*/locations/*/repositories/*/workflowInvocations/*`.
      case workflowInvocation(Swift.String)
      /// The error status encountered upon this attempt to create the
      /// workflow invocation, if the attempt was unsuccessful.
      indirect case errorStatus(GoogleRpc.Status?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataform.v1.WorkflowConfig.ScheduledExecutionRecord"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataform.v1.WorkflowConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
